spring:
  profiles: company
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/batch?autoReconnect=true&serverTimezone=UTC
    username: root
    password: wjddyd.1204
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 10
      validation-query: select 1 from dual
      test-while-idle: true
      max-wait: 10000

server:
  port: 8081


# MyBatis Configuration
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

excel:
  template-path: /Users/imc053/IdeaProjects/batch/src/main/resources/excelTemplate/
  output-path: /Users/imc053/Desktop/xmlFile/

---

spring:
  profiles: home
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/batch?autoReconnect=true&serverTimezone=UTC
    username: root
    password: ghzkrp153
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 10
      validation-query: select 1 from dual
      test-while-idle: true
      max-wait: 10000

server:
  port: 8081

# MyBatis Configuration
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

excel:
  template-path: /Users/jungyong/IdeaProjects/batch/src/main/resources/excelTemplate/
  output-path: /Users/jungyong/Desktop/

---

spring:
  profiles: prd
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/batch?autoReconnect=true&serverTimezone=UTC
    username: root
    password: ghzkrp153
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 10
      validation-query: select 1 from dual
      test-while-idle: true
      max-wait: 10000

server:
  port: 8081

# MyBatis Configuration
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

excel:
  template-path: /Users/jungyong/IdeaProjects/batch/src/main/resources/excelTemplate/
  output-path: /Users/jungyong/Desktop/sportExcel/