spring:
  onfig.activate.on-profile: company
  profiles: company
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  batch:
    job:
      enabled: false
  datasource:
    url: ENC(zk/Fc8WyhfkE1ffRs4T3wtC3d1SkVINepuxfTxOWtIpR2quOQx6MlRDmvFiRhP7q7U8zOC+NOSfUvY7SvYeO6oCxJ5Fp8Y4anr422G4qEGn5EaQhPm/OvA==)
    username: ENC(Xgg3IP4bBX4B3KNrg60A3g==)
    password: ENC(CMpj8ee6yEHqEVp7BZgXeA7dv14zkss4)
#    url: jdbc:mysql://jungyongbox.cwpqs9pmrl3s.ap-northeast-2.rds.amazonaws.com:3306
#    username: admin
#    password: Wjddyd!0619
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 10
      validation-query: select 1 from dual
      test-while-idle: true
      max-wait: 10000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

server:
  port: 8081


# MyBatis Configuration
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

excel:
  template-path: /Users/imc053/IdeaProjects/batch/src/main/resources/excelTemplate/
  output-path: /Users/imc053/Desktop/xmlFile/

---

spring:
  profiles: home
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  batch:
    job:
      enabled: false
  datasource:
    url: ENC(zk/Fc8WyhfkE1ffRs4T3wtC3d1SkVINepuxfTxOWtIpR2quOQx6MlRDmvFiRhP7q7U8zOC+NOSfUvY7SvYeO6oCxJ5Fp8Y4anr422G4qEGn5EaQhPm/OvA==)
    username: ENC(Xgg3IP4bBX4B3KNrg60A3g==)
    password: ENC(CMpj8ee6yEHqEVp7BZgXeA7dv14zkss4)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 10
      validation-query: select 1 from dual
      test-while-idle: true
      max-wait: 10000

server:
  port: 8081

# MyBatis Configuration
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/**

excel:
  template-path: /Users/jungyong/IdeaProjects/batch/src/main/resources/excelTemplate/
  output-path: /Users/jungyong/Desktop/

---

spring:
  profiles: prd
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  batch:
    job:
      enabled: false
  datasource:
    url: ENC(zk/Fc8WyhfkE1ffRs4T3wtC3d1SkVINepuxfTxOWtIpR2quOQx6MlRDmvFiRhP7q7U8zOC+NOSfUvY7SvYeO6oCxJ5Fp8Y4anr422G4qEGn5EaQhPm/OvA==)
    username: ENC(Xgg3IP4bBX4B3KNrg60A3g==)
    password: ENC(CMpj8ee6yEHqEVp7BZgXeA7dv14zkss4)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 10
      validation-query: select 1 from dual
      test-while-idle: true
      max-wait: 10000

server:
  port: 8081
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
# MyBatis Configuration
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

excel:
  template-path: /Users/jungyong/IdeaProjects/batch/src/main/resources/excelTemplate/
  output-path: /Users/jungyong/Desktop/sportExcel/