<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Title</title>
</head>
<body>
<table border="1">
    <tr>
        <th>job명</th>
        <th>옵션</th>
        <th>실행버튼</th>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
    <tr>
        <td>1</td>
        <td>김영희</td>
        <td>김영희</td>
    </tr>
</table>
</body>
</html>